### ISSUE TITLE
DeepHYperXvis.py missing

### ISSUE THREAD

**Issue by ghost** [daniel-rychlewski/hsi-toolbox#1] opened 2020-06-01 05:58 UTC
Hi Daniel,

Thanks for sharing your toolbox. The following error is produced when doing a simple run.

/hsi-toolbox-master/DeepHyperXvis.py': [Errno 2] No such file or directory

I've also edited out all the references to DeepHyperX as there is no associated py file such as: DeepHyperX.batch, DeepHyperX.datasets, DeepHyperX.image_compression.

Are there some files missing?

Cheers,

Bbop

**Comment by daniel-rychlewski** [comment] 2020-06-01 07:47
Hello Bbop,

Thanks for your kind feedback. I have tried to reproduce the error by downloading the project and running DeepHyperX/main.py and was not able to do it, because even if I delete vis.py, the main program does not complain about the file being missing. The three files batch.py, datasets.py and image_compression.py are present in the DeepHyperX directory of the repository (https://github.com/daniel-rychlewski/hsi-toolbox/tree/master/DeepHyperX), so may I suggest that you check if they are present on your machine and share any relevant details on how to reproduce the issue (file name of the program you ran, arguments used, OS, Python environment - version and packages installed)?

Kind regards,
Daniel Rychlewski

**Comment by ghost** [comment] 2020-06-01 08:39
Thanks Daniel,

I moved the vis.py to the parent directory and renamed it DeepHyperXvis.py and that worked.

I am working on band selection and NN for a custom data set and not using distiller at all.

I'm not really good at python and will list out issues I've run into and maybe I can help others. 

I will get more detail as I work through it. Thanks for responding =)

There were some requirement issues such as protobuf and winml and I installed the some packages manually. I will repeat the environment setup to get details. One I remember clearly is manually installing pytorch.

I also edited the batch.py to contain my system details.

Python 3.6.10 :: Anaconda, Inc.

     active environment : anotherOne
    active env location : C:\Users\bbop1\anaconda3\envs\anotherOne
            shell level : 1
       user config file : C:\Users\bbop1\.condarc
 populated config files : C:\Users\bbop1\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\Users\bbop1\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\bbop1\anaconda3\pkgs
                          C:\Users\bbop1\.conda\pkgs
                          C:\Users\bbop1\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\bbop1\anaconda3\envs
                          C:\Users\bbop1\.conda\envs
                          C:\Users\bbop1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
astropy                   4.0.1.post1      py36h68a101e_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
bqplot                    0.12.12                  pypi_0    pypi
brotlipy                  0.7.0           py36h779f372_1000    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
cffi                      1.14.0           py36ha419a9e_0    conda-forge
chardet                   3.0.4           py36h9f0ad1d_1006    conda-forge
colorama                  0.4.3                      py_0    conda-forge
confuse                   1.1.0              pyh9f0ad1d_0    conda-forge
cryptography              2.9.2            py36hef61171_0    conda-forge
cudatoolkit               10.2.89              h74a9793_1
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
deprecated                1.2.10                   pypi_0    pypi
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
fire                      0.3.1                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitdb2                    4.0.2                    pypi_0    pypi
gitpython                 2.1.11                   pypi_0    pypi
google-auth               1.16.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.29.0                   pypi_0    pypi
gym                       0.12.5                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
htmlmin                   0.1.12                     py_1    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                        py_1    conda-forge
imagehash                 4.1.0              pyh9f0ad1d_0    conda-forge
imageio                   2.8.0                    pypi_0    pypi
importlib-metadata        1.6.0            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
intel-openmp              2020.1                      216
ipykernel                 5.3.0            py36h5ca1d4c_0    conda-forge
ipython                   7.14.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.0           py36h9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonpatch                 1.25                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
jsonschema                3.2.0            py36h9f0ad1d_1    conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keras2onnx                1.6.1                    pypi_0    pypi
kiwisolver                1.2.0            py36h246c5b5_0    conda-forge
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libtiff                   4.1.0                h56a325e_0
lightgbm                  2.3.1                    pypi_0    pypi
llvmlite                  0.32.1           py36ha925a31_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py36h68a101e_1    conda-forge
matplotlib-base           3.2.1            py36hf0cddfc_0    conda-forge
missingno                 0.4.2                      py_1    conda-forge
mistune                   0.8.4           py36h68a101e_1001    conda-forge
mkl                       2020.1                      216
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.15           py36h14836fe_0
mkl_random                1.1.1            py36h47e9c7a_0
mlxtend                   0.17.2                   pypi_0    pypi
more-itertools            8.3.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
munch                     2.5.0                    pypi_0    pypi
nbconvert                 5.6.1            py36h9f0ad1d_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
networkx                  2.4                        py_1    conda-forge
ninja                     1.9.0            py36h74a9793_0
notebook                  6.0.3            py36h9f0ad1d_0    conda-forge
numba                     0.49.1           py36h47e9c7a_0
numpy                     1.18.1           py36h93ca92e_0
numpy-base                1.18.1           py36hc3f5095_1
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py36_0
onnx                      1.5.0                    pypi_0    pypi
onnx-tf                   1.5.0                    pypi_0    pypi
onnxconverter-common      1.6.1                    pypi_0    pypi
onnxmltools               1.5.1                    pypi_0    pypi
onnxruntime               1.3.0                    pypi_0    pypi
openssl                   1.1.1g               he774522_0    conda-forge
opt-einsum                3.2.1                    pypi_0    pypi
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.3            py36h47e9c7a_0
pandas-profiling          2.8.0                      py_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
phik                      0.10.0                     py_0    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pillow                    7.1.2            py36hcc1f983_0
pip                       20.0.2                   py36_3
pluggy                    0.13.1                   pypi_0    pypi
pretrainedmodels          0.7.4                    pypi_0    pypi
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
protobuf                  3.8.0                    pypi_0    pypi
py                        1.8.1                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_0    conda-forge
pydot                     1.4.1                    pypi_0    pypi
pyglet                    1.5.5                    pypi_0    pypi
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py36h68a101e_0    conda-forge
pysocks                   1.7.1            py36h9f0ad1d_1    conda-forge
pytest                    5.4.2                    pypi_0    pypi
python                    3.6.10               h9f7ef89_2
python-dateutil           2.8.1                      py_0
python-graphviz           0.14                     pypi_0    pypi
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.5.0           py3.6_cuda102_cudnn7_0    pytorch
pytz                      2020.1                     py_0
pywavelets                1.1.1            py36h7725771_1    conda-forge
pywin32                   227                      pypi_0    pypi
pywinpty                  0.5.7                    py36_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
qgrid                     1.3.1                    pypi_0    pypi
qtconsole                 4.7.4                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.22.1           py36h6288b17_0
scipy                     1.4.1            py36h9439919_0
seaborn                   0.10.1                     py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.4.0                   py36_0
six                       1.14.0                   py36_0
skl2onnx                  1.6.1                    pypi_0    pypi
smmap                     3.0.4                    pypi_0    pypi
spectral                  0.21                     pypi_0    pypi
sqlite                    3.31.1               h2a8f88b_1
statsmodels               0.11.1           py36h68a101e_1    conda-forge
tabulate                  0.8.7                    pypi_0    pypi
tangled-up-in-unicode     0.0.6              pyh9f0ad1d_0    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0.post3              pypi_0    pypi
tensorflow                2.2.0                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                      py_0    conda-forge
tf2onnx                   1.5.3                    pypi_0    pypi
tifffile                  2020.5.25                pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
torchfile                 0.1.0                    pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.6.0                py36_cu102    pytorch
tornado                   6.0.4            py36hfa6e2cd_0    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
traittypes                0.2.1                    pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
typing-extensions         3.7.4.2                  pypi_0    pypi
umap                      0.1.1                    pypi_0    pypi
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h0510ff6_4
visdom                    0.1.8.9                  pypi_0    pypi
visions                   0.4.4              pyh9f0ad1d_0    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_2
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                    pypi_0    pypi
websocket-client          0.57.0                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0
widgetsnbextension        3.5.1                    py36_0    conda-forge
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2              py36h7fe50ca_0
winmltools                1.5.1                    pypi_0    pypi
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xlsxwriter                1.2.8                    pypi_0    pypi
xz                        5.2.5                h62dcd97_0
yaml                      0.2.4                he774522_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7                h508b16e_0

Issue 1 - main.py line 

it does not find the DeepHyperX.X files and I removed the DeepHyperX in the name and they worked. As below.

from DeepHyperX.batch import STORE_EXPERIMENT_LOCATION, \
    PYTHON_INTERPRETER_LOCATION, VIS_PY_LOCATION
from DeepHyperX.datasets import get_dataset, HyperX, open_file, DATASETS_CONFIG
from DeepHyperX.image_compression import apply_band_selection_choice
from DeepHyperX.models import get_model, train, test, save_model
from DeepHyperX.utils import metrics, convert_to_color_, convert_from_color_, \
    display_dataset, display_predictions, explore_spectrums, plot_spectrums, \
    sample_gt, build_dataset, show_results, compute_imf_weights, get_device, start_mem_measurement, stop_mem_measurement
from DeepHyperX.utils import print_memory_metrics

from batch import STORE_EXPERIMENT_LOCATION, \
    PYTHON_INTERPRETER_LOCATION, VIS_PY_LOCATION
from datasets import get_dataset, HyperX, open_file, DATASETS_CONFIG
from image_compression import apply_band_selection_choice
from models import get_model, train, test, save_model
from utils import metrics, convert_to_color_, convert_from_color_, \
    display_dataset, display_predictions, explore_spectrums, plot_spectrums, \
    sample_gt, build_dataset, show_results, compute_imf_weights, get_device, start_mem_measurement, stop_mem_measurement
from utils import print_memory_metrics

Issue 2 - main.py

from pandas.tests.sparse.frame.test_to_from_scipy import scipy

pandas.tests.sparse.frame.test_to_from_scipy didn't work.

I removed it and just imported scipy and it worked.

Issue 3 - main.py line 633 conf_temp.get_values()

pandas.get_values() is deprecated.
https://pandas.pydata.org/pandas-docs/version/0.25.3/reference/api/pandas.DataFrame.get_values.html

replaced  with conf_temp.values

My test arguments have been:

python main.py --download PaviaC
python main.py --model nn --dataset PaviaC --training_sample 0.1 --cuda 0

Cheers,

Chris

**Comment by daniel-rychlewski** [comment] 2020-06-01 09:16
Hello Chris,

Thank you very much for sharing your experiences, I do hope your comment will help someone else out. For me, the command "python main.py --model nn --dataset PaviaC --training_sample 0.1 --cuda 0 --epoch 1" did work without issues, though. The fact that there is no path delimiter in the file 'DeepHyperXvis.py' makes me wonder if perhaps the path in batch.py is set correctly in the sense that either `'/'` or `'\\'` needs to be the line delimiter, not just a plain backslash `'\'` because that's the escape character and 'DeepHyperX\vis.py' probably wouldn't work (might ask for DeepHyperXvis.py), while both `'DeepHyperX/vis.py'` and `'DeepHyperX\\vis.py'` probably should work fine on Windows. Could you try that out please?

Issue 2: For me, 'conda list' does show the line
"pandas                    0.24.2                   pypi_0    pypi"
but I do see that you're using a newer version of pandas than that.

Issue 3: Thanks for your input, it's probably wise to replace get_values() with .values. However, I cannot promise that I will be updating the project to eliminate deprecation warnings.

Kind regards,
Daniel Rychlewski

**Comment by ghost** [comment] 2020-06-01 14:17
Hi Daniel,

Thanks for explaining. I've input a new custom dataset, however it throws the following error:

(anotherOne) C:\Users\bbop1\hsi-toolbox-master\DeepHyperX>python main.py --model nn --dataset selene --training_sample 0.1 --cuda 0
C:\Users\bbop1\anaconda3\envs\anotherOne\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Computation on CUDA GPU device 0
Setting up a new session...
Traceback (most recent call last):
  File "main.py", line 224, in <module>
    FOLDER)
  File "C:\Users\bbop1\hsi-toolbox-master\DeepHyperX\datasets.py", line 192, in get_dataset
    img, gt, rgb_bands, ignored_labels, label_values, palette = CUSTOM_DATASETS_CONFIG[dataset_name]['loader'](folder)
  File "C:\Users\bbop1\hsi-toolbox-master\DeepHyperX\custom_datasets.py", line 90, in <lambda>
    'loader': lambda folder: selene_loader(folder)
  File "C:\Users\bbop1\hsi-toolbox-master\DeepHyperX\custom_datasets.py", line 460, in selene_loader
    img = open_file(folder + CUSTOM_DATASETS_CONFIG['selene']['img'])['selene']
KeyError: 'selene'

Knowing that PaviaC works well, I tried renaming it the same as PaviaC however it stll won't work. Do you know why this may be occuring?

Thanks,

Chris

**Comment by ghost** [comment] 2020-06-01 14:19
'selene': {
        'img': 'selene.mat',
        'gt': 'selene_gt.mat',
        'download': False,
        'loader': lambda folder: selene_loader(folder)
    },

def selene_loader(folder):
    img = open_file(folder + CUSTOM_DATASETS_CONFIG['selene']['img'])['selene']
    gt = open_file(folder + CUSTOM_DATASETS_CONFIG['selene']['gt'])['selene_gt']
    gt = gt.astype('uint8')

    rgb_bands = (47, 27, 13)

    label_values = ["Unclassified",
                    "Green Ceramic",
                    "Grey Ceramic",
                    "Orange Perspex",
                    "Green Perspex",]
    ignored_labels = []
    palette = None

    return img, gt, rgb_bands, ignored_labels, label_values, palette

**Comment by daniel-rychlewski** [comment] 2020-06-01 14:27
Hello Chris,

I'm glad I could help. As for the integration of a new dataset, I do think you have followed the steps correctly, i.e. to add the dataset file and expand the custom loader, so my guess is that the dataset file does actually not have the key 'selene' and that's ok because that varies by dataset, even for the existing datasets in custom_datasets.py if you look at the loaders. It means that
`open_file(folder + CUSTOM_DATASETS_CONFIG['selene']['img'])`
has already given you the dataset to read in. Perhaps there is no key or the key is named differently - I suggest that you set a breakpoint / add a watch for the above line to evaluate what you actually get. Then you'll see how the key is called or if there is a key at all.

Kind regards,
Daniel Rychlewski

**Comment by daniel-rychlewski** [comment] 2020-06-01 14:37
Since the original problem is resolved, I am closing the issue.

**Closed as completed by daniel-rychlewski** 2020-06-01 14:37 UTC

**Comment by ghost** [comment] 2020-06-01 17:17
Thanks Daniel,

How are they keys created? I've tried googling but don't know what it means.

I remove the keys and get the following error:

(anotherOne) C:\Users\bbop1\hsi-toolbox-master\DeepHyperX>python main.py --model nn --dataset selene --training_sample 0.1 --cuda 0
C:\Users\bbop1\anaconda3\envs\anotherOne\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Computation on CUDA GPU device 0
Setting up a new session...
Traceback (most recent call last):
  File "main.py", line 224, in <module>
    FOLDER)
  File "C:\Users\bbop1\hsi-toolbox-master\DeepHyperX\datasets.py", line 213, in get_dataset
    nan_mask = np.isnan(img.sum(axis=-1))
AttributeError: 'dict' object has no attribute 'sum'

Ground Truth was created in Matlab by manually labeling pixels with 1-4.

**Comment by daniel-rychlewski** [comment] 2020-06-01 17:30
Hello Chris,

Python can store Key-Value-Pairs in dictionaries. You use the key to access the value stored for that key or store a value. Please google "Python dictionary" to find out about this concept and examples, which might help to clarify. If you know a different programming language like Java, the equivalent to dictionaries would be a Map.

The error message you're posting says that 'img' is a dictionary, but you would need a numpy array so that its contents (pixels) could be summed up using the sum function. This makes me guess that there is a key you need to use to correctly access the actual contents of the dataset first, i.e. all pixels of the dataset in a multidimensional array. However, it is up to you to find out how you get this array which constitutes the dataset.

Kind regards,
Daniel Rychlewski

**Comment by ghost** [comment] 2020-06-01 18:50
Thanks heaps Daniel, you're a legend.

The mat files held onto their original label when I renamed them for python.
